<a href="https://colab.research.google.com/github/DrashtiSanjayShah/fake-news-AIDS/blob/main/Fake_news_(AIDS2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import re
import seaborn as sns
import string
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv("/content/data.csv")

In [ ]:
df.head()

URLs  \
0  http://www.bbc.com/news/world-us-canada-414191...   
1  https://www.reuters.com/article/us-filmfestiva...   
2  https://www.nytimes.com/2017/10/09/us/politics...   
3  https://www.reuters.com/article/us-mexico-oil-...   
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...   

                                            Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   URLs      4009 non-null   object
 1   Headline  4009 non-null   object
 2   Body      3988 non-null   object
 3   Label     4009 non-null   int64 
dtypes: int64(1), object(3)
memory usage: 125.4+ KB


In [ ]:
df.shape

(4009, 4)

In [ ]:
df['Label'].value_counts()

0    2137
1    1872
Name: Label, dtype: int64

In [ ]:
df.isnull().sum()

URLs         0
Headline     0
Body        21
Label        0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

URLs        0
Headline    0
Body        0
Label       0
dtype: int64

In [ ]:
df.reset_index(inplace=True)
df.head()

index                                               URLs  \
0      0  http://www.bbc.com/news/world-us-canada-414191...   
1      1  https://www.reuters.com/article/us-filmfestiva...   
2      2  https://www.nytimes.com/2017/10/09/us/politics...   
3      3  https://www.reuters.com/article/us-mexico-oil-...   
4      4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...   

                                            Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

In [ ]:
df = df.drop(['URLs','index','Body'],axis = 1)
df.head()

Headline  Label
0         Four ways Bob Corker skewered Donald Trump      1
1  Linklater's war veteran comedy speaks to moder...      1
2  Trump’s Fight With Corker Jeopardizes His Legi...      1
3  Egypt's Cheiron wins tie-up with Pemex for Mex...      1
4        Jason Aldean opens 'SNL' with Vegas tribute      1

1. TOKENIZATION

In [ ]:
sample_data = 'This is for AIDS2 mini project'
sample_data = sample_data.split()
sample_data

['This', 'is', 'for', 'AIDS2', 'mini', 'project']

2. MAKE LOWERCASE

In [ ]:
sample_data = [data.lower() for data in sample_data]
sample_data

['this', 'is', 'for', 'aids2', 'mini', 'project']

3. REMOVE STOPWORDS

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words[0:10])
print(len(stop_words))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]
179


In [ ]:
sample_data = [data for data in sample_data if data not in stop_words]
print(sample_data)
len(sample_data)

['aids2', 'mini', 'project']


3

4. STEMMING

In [ ]:
ps = PorterStemmer()
sample_data_stemming = [ps.stem(data) for data in sample_data]
print(sample_data_stemming)

['aids2', 'mini', 'project']


5. LEMMATIZATION

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lm = WordNetLemmatizer()
sample_data_lemma = [lm.lemmatize(data) for data in sample_data]
print(sample_data_lemma)

['aids2', 'mini', 'project']


In [ ]:
lm = WordNetLemmatizer()
corpus = []
for i in range (len(df)):
    review = re.sub('^a-zA-Z0-9',' ', df['Headline'][i])
    review = review.lower()
    review = review.split()
    review = [lm.lemmatize(x) for x in review if x not in stop_words]
    review = " ".join(review)
    corpus.append(review)

In [ ]:
len(corpus)

3988

In [ ]:
corpus[0]

'four way bob corker skewered donald trump'

VECTORIZATION

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(corpus).toarray()
x

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.31982335, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
y = df['Label']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Label, dtype: int64

TRAIN TEST SPLIT

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=10,stratify=y)

In [ ]:
len(x_train),len(y_train)

(2791, 2791)

In [ ]:
len(x_test),len(y_test)

(1197, 1197)

MODEL BUILDING

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf.predict(x_test)
accuracy_score_ = accuracy_score(y_test,y_pred)
accuracy_score_

0.8320802005012531

In [ ]:
class Evaluation:

    def __init__(self,model,x_train,x_test,y_train,y_test):
        self.model = model
        self.x_train = x_train
        self.x_test = x_test
        self.y_train = y_train
        self.y_test = y_test

    def train_evaluation(self):
        y_pred_train = self.model.predict(self.x_train)

        acc_scr_train = accuracy_score(self.y_train,y_pred_train)
        print("Accuracy Score On Training Data Set :",acc_scr_train)
        print()

        con_mat_train = confusion_matrix(self.y_train,y_pred_train)
        print("Confusion Matrix On Training Data Set :\n",con_mat_train)
        print()

        class_rep_train = classification_report(self.y_train,y_pred_train)
        print("Classification Report On Training Data Set :\n",class_rep_train)


    def test_evaluation(self):
        y_pred_test = self.model.predict(self.x_test)

        acc_scr_test = accuracy_score(self.y_test,y_pred_test)
        print("Accuracy Score On Testing Data Set :",acc_scr_test)
        print()

        con_mat_test = confusion_matrix(self.y_test,y_pred_test)
        print("Confusion Matrix On Testing Data Set :\n",con_mat_test)
        print()

        class_rep_test = classification_report(self.y_test,y_pred_test)
        print("Classification Report On Testing Data Set :\n",class_rep_test)


ACCURACY OF TRAINING DATA

In [ ]:
Evaluation(rf,x_train, x_test, y_train, y_test).train_evaluation()

Accuracy Score On Training Data Set : 1.0

Confusion Matrix On Training Data Set :
 [[1484    0]
 [   0 1307]]

Classification Report On Training Data Set :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1484
           1       1.00      1.00      1.00      1307

    accuracy                           1.00      2791
   macro avg       1.00      1.00      1.00      2791
weighted avg       1.00      1.00      1.00      2791



ACCURACY OF TESTING DATA

In [ ]:
Evaluation(rf,x_train, x_test, y_train, y_test).test_evaluation()

Accuracy Score On Testing Data Set : 0.8320802005012531

Confusion Matrix On Testing Data Set :
 [[557  79]
 [122 439]]

Classification Report On Testing Data Set :
               precision    recall  f1-score   support

           0       0.82      0.88      0.85       636
           1       0.85      0.78      0.81       561

    accuracy                           0.83      1197
   macro avg       0.83      0.83      0.83      1197
weighted avg       0.83      0.83      0.83      1197



PROCESSING PIPELINE

In [ ]:
class Preprocessing:

    def __init__(self,data):
        self.data = data

    def text_preprocessing_user(self):
        lm = WordNetLemmatizer()
        pred_data = [self.data]
        preprocess_data = []
        for data in pred_data:
            review = re.sub('^a-zA-Z0-9',' ', data)
            review = review.lower()
            review = review.split()
            review = [lm.lemmatize(x) for x in review if x not in stop_words]
            review = " ".join(review)
            preprocess_data.append(review)
        return preprocess_data

In [ ]:
df.columns

Index(['Headline', 'Label'], dtype='object')

In [ ]:
df['Headline'][1]

"Linklater's war veteran comedy speaks to modern America, says star"

In [166]:
data = "Linklater's war veteran comedy speaks to modern America, says star"
Preprocessing(data).text_preprocessing_user()

["linklater's war veteran comedy speaks modern america, say star"]

In [167]:
class Prediction:

    def __init__(self,pred_data, model):
        self.pred_data = pred_data
        self.model = model

    def prediction_model(self):
        preprocess_data = Preprocessing(self.pred_data).text_preprocessing_user()
        data = tf.transform(preprocess_data)
        prediction = self.model.predict(data)

        if prediction [0] == 0 :
            return "The News Is Fake"

        else:
            return "The News Is Real"

In [168]:
data = "linklater's war veteran comedy speaks modern america, say star"
Prediction(data,rf).prediction_model()

'The News Is Real'

In [169]:
df.tail()

Headline  Label
3983  CNN and Globalist Exposed - Steve Quayle and A...      0
3984                                    Trends to Watch      0
3985  Trump Jr. Is Soon To Give A 30-Minute Speech F...      0
3986  China to accept overseas trial data in bid to ...      1
3987  Vice President Mike Pence Leaves NFL Game Beca...      0

In [170]:
df['Headline'][3983]

'CNN and Globalist Exposed - Steve Quayle and Alex Jones'

In [171]:
user_data = 'CNN and Globalist Exposed - Steve Quayle and Alex Jones'
Prediction(user_data,rf).prediction_model()

'The News Is Fake'